// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import AsyncStorage from '@react-native-async-storage/async-storage';
import type { Database } from './types';

const SUPABASE_URL = "https://jkuasxwlcftqxkuxzlyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprdWFzeHdsY2Z0cXhrdXh6bHloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzAzMDMsImV4cCI6MjA2NjAwNjMwM30.yW8qYonEXXeHCYUJjv8b-02f7BUYAWuAB1-78zqqYwU";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: AsyncStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
});